### ISSUE TITLE
Upstream to nixpkgs

### ISSUE THREAD

**Issue by Pandapip1** [nix-community/steam-fetcher#6]
Any chance you could upstream this to nixpkgs? If not, would it be okay if I upstreamed it?

**Comment by aidalgol** [comment]
I don't think this belongs in nixpkgs, because this is really meant only for game servers (you should use Steam to run Steam games, because the Steam NixOS module already has all the hacks needed to make things work), and I don't think proprietary game servers only available through Steam should go in nixpkgs, at least not without incubating in nix-community for a while first.

If someone wants to add this or another steam fetcher to nixpkgs, I will not complain, but I would like to continue maintaining this fetcher in nix-community for the time being.
